CREATE TABLE IF NOT EXISTS chat (
	id INTEGER PRIMARY KEY,
	chat_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS lcdailyquestion (
	id INTEGER PRIMARY KEY,
	'date' TEXT NOT NULL,
	title TEXT NOT NULL,
	question_id TEXT NOT NULL,
	difficulty TEXT NOT NULL,
	url TEXT NOT NULL
);
